# Generated by Django 4.2 on 2024-10-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
